# cloudbuild.api.yaml
# Build + push API image, then deploy to Cloud Run service.
# Expected Dockerfile: docker/Dockerfile.api
# Build context: repository root (.)

substitutions:
  _REGION: "asia-south1"
  _SERVICE: "honeypot-rq-api"
  _IMAGE: "gcr.io/$PROJECT_ID/honeypot-rq-api:$COMMIT_SHA"

steps:
  # Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "${_IMAGE}",
        "-f", "docker/Dockerfile.api",
        "."
      ]

  # Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE}"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      [
        "run", "deploy", "${_SERVICE}",
        "--image", "${_IMAGE}",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated"
      ]

images:
  - "${_IMAGE}"