substitutions:
  _REGION: "asia-south1"
  _SERVICE: "honeypot-rq-worker"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/honeypot-rq-worker:$COMMIT_SHA",
        "-f", "docker/Dockerfile.worker",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/honeypot-rq-worker:$COMMIT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      [
        "run", "deploy", "${_SERVICE}",
        "--image", "gcr.io/$PROJECT_ID/honeypot-rq-worker:$COMMIT_SHA",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--no-allow-unauthenticated"
      ]

images:
  - "gcr.io/$PROJECT_ID/honeypot-rq-worker:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY