# Broken-Flow States
BF_S0 = "BF_S0" # Init / Detecting
BF_S1 = "BF_S1" # Engagement Started
BF_S2 = "BF_S2" # Deep Engagement / Intel Extraction
BF_S3 = "BF_S3" # Alternative Path (after slight resistance or repeat)
BF_S4 = "BF_S4" # Secondary Failure
BF_S5 = "BF_S5" # Closing / Finalize

# Intents
INT_ACK_CONCERN = "INT_ACK_CONCERN"
INT_REFUSE_SENSITIVE_ONCE = "INT_REFUSE_SENSITIVE_ONCE"
INT_CHANNEL_FAIL = "INT_CHANNEL_FAIL"
INT_ASK_OFFICIAL_WEBSITE = "INT_ASK_OFFICIAL_WEBSITE"
INT_ASK_OFFICIAL_HELPLINE = "INT_ASK_OFFICIAL_HELPLINE"
INT_ASK_TICKET_REF = "INT_ASK_TICKET_REF"
INT_ASK_DEPARTMENT_BRANCH = "INT_ASK_DEPARTMENT_BRANCH"
INT_ASK_ALT_VERIFICATION = "INT_ASK_ALT_VERIFICATION"
INT_SECONDARY_FAIL = "INT_SECONDARY_FAIL"
INT_CLOSE_AND_VERIFY_SELF = "INT_CLOSE_AND_VERIFY_SELF"
